# Generated by Django 3.1.2 on 2020-10-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_link', models.CharField(max_length=1023, unique=True, verbose_name='Long Link')),
                ('short_link', models.CharField(max_length=255, unique=True, verbose_name='Short Link')),
                ('link_redirects', models.PositiveIntegerField(verbose_name='Count Link Redirects')),
            ],
        ),
    ]
