# Generated by Django 3.1.2 on 2020-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_redirects',
            field=models.PositiveIntegerField(default=0, verbose_name='Count Link Redirects'),
        ),
    ]
