# Generated by Django 3.1.2 on 2020-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linxes', '0002_auto_20201028_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=255, verbose_name='Short Link'),
        ),
    ]
