# Generated by Django 3.1.2 on 2020-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linxes', '0003_auto_20201028_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=255, unique=True, verbose_name='Short Link'),
        ),
    ]
